# Bonus exercise: From banking queries to JSON

## Data

### Load and visualize data

In [46]:
# constants
INTENTS = (
"card_arrival",
"card_not_working",
"lost_or_stolen_card",
"pin_blocked",
"cancel_transfer",
"edit_personal_details",
"request_refund",
"terminate_account",
"transaction_charged_twice",
"exchange_rate"
)

RANDOM_SEED = 42

In [61]:
import pandas as pd

def load_and_filter_data(split="train", intents=INTENTS) -> pd.DataFrame:
  url = f"https://raw.githubusercontent.com/PolyAI-LDN/task-specific-datasets/refs/heads/master/banking_data/{split}.csv"
  data = pd.read_csv(url)
  filtered_data = data[data.category.isin(intents)]
  return filtered_data

In [ ]:
data_train = load_and_filter_data()
data_test = load_and_filter_data("test")

In [70]:
print("Training data :")
display(data_train.head())
display(data_train.describe())
print("Test data:")
display(data_test.head())
display(data_test.describe())

Training data :

                                                text      category
0                     I am still waiting on my card?  card_arrival
1  What can I do if my card still hasn't arrived ...  card_arrival
2  I have been waiting over a week. Is the card s...  card_arrival
3  Can I track my card while it is in the process...  card_arrival
4  How do I know if I will get my card, or if it ...  card_arrival

                                  text                   category
count                             1304                       1304
unique                            1304                         10
top     I am still waiting on my card?  transaction_charged_twice
freq                                 1                        175

Test data:

                                                text      category
0                           How do I locate my card?  card_arrival
1  I still have not received my new card, I order...  card_arrival
2  I ordered a card but it has not arrived. Help ...  card_arrival
3   Is there a way to know when my card will arrive?  card_arrival
4                       My card has not arrived yet.  card_arrival

                            text      category
count                        400           400
unique                       400            10
top     How do I locate my card?  card_arrival
freq                           1            40

### Training and validation split

In [77]:
from sklearn.model_selection import train_test_split

X_train, X_val = train_test_split(data_train, test_size=0.2, random_state=42)
print("X_train number of queries:")
print(X_train.count(), "\n")
print("X_val number of queries:")
print(X_val.count(), "\n")

X_train number of queries:
text        1043
category    1043
dtype: int64

X_val number of queries:
text        261
category    261
dtype: int64

## Training